import { Metadata } from "next";

import "@/styles/globals.css";

import Footer from "../_components/footer";

export const metadata: Metadata = {
  title: "Preview",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.png",
  },
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <main className="container relative h-[700px] max-w-screen-sm bg-background px-0 @container md:overflow-hidden md:rounded-xl md:shadow-xl">
        {children}
      </main>
      <Footer />
    </>
  );
}
